# Exporter configuration for bin/export. Copy this file and name it "config.yml".
username: 'FINDOLOGIC_API'
password: '1234'
domain: 'findologic.plentymarkets-cloud02.com'
multiShopId: 0
availabilityId: ~
priceId: 1
rrpId: 2
language: 'DE'
debug: true
customerLoginUri: ~ # Set this to the path of the customerLogin, that returns the configuration for the importer.
#protocol: 'http' # Uncomment to force the protocol. Needs to be either http or https.
